/**
 * This File is autogenerated by ./bin/openapi-parser.ts
 * Should not be modified.
 */

export const OpenAPI = {
  "openapi": "3.0.3",
  "info": {
    "title": "PSBAPP VirGym API",
    "version": "2021-05-27"
  },
  "paths": {
    "/p/{placeId}": {
      "parameters": [
        {
          "in": "path",
          "schema": {
            "type": "string"
          },
          "name": "placeId",
          "required": true
        }
      ],
      "get": {
        "tags": [
          "End User"
        ],
        "security": [
          {
            "userApiKey": []
          }
        ],
        "description": "Ottieni informazioni su un luogo",
        "responses": {
          "200": {
            "description": "Informazioni sul luogo",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "placeId": {
                      "type": "string"
                    },
                    "building": {
                      "type": "string"
                    },
                    "city": {
                      "type": "string"
                    },
                    "street": {
                      "type": "string"
                    },
                    "streetNumber": {
                      "type": "string"
                    },
                    "province": {
                      "type": "string"
                    },
                    "phone": {
                      "type": "string"
                    },
                    "lat": {
                      "type": "string"
                    },
                    "lon": {
                      "type": "string"
                    },
                    "category": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "website": {
                      "type": "string",
                      "format": "uri"
                    },
                    "istatCode": {
                      "type": "string"
                    },
                    "representative": {
                      "type": "string"
                    },
                    "cpu": {
                      "type": "string"
                    },
                    "openingTimeDesc": {
                      "type": "string",
                      "description": "La descrizione testuale degli orari di apertura"
                    },
                    "allowBookingByPhone": {
                      "type": "boolean",
                      "description": "Consentire o meno la registrazione tramite SMS",
                      "default": false
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/p/{placeId}/slots": {
      "parameters": [
        {
          "in": "path",
          "schema": {
            "type": "string"
          },
          "name": "placeId",
          "required": true
        }
      ],
      "get": {
        "parameters": [
          {
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date"
            },
            "name": "from",
            "required": true
          },
          {
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date"
            },
            "name": "to",
            "required": false
          }
        ],
        "tags": [
          "End User"
        ],
        "security": [
          {
            "userApiKey": []
          }
        ],
        "description": "Ottieni la lista degli slot selezionabili, a partire dalla data indicata nel query parameter `from`, fino alla data specificata nel query parameter (opzionale) `to`",
        "responses": {
          "200": {
            "description": "Lista delle prenotazioni disponibili",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "slots": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "slotId": {
                            "type": "string",
                            "description": "L'id dello specifico slot. E' univoco solamente per un determinato Place."
                          },
                          "startDatetime": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Orario di inizio dello slot in UTC seguendo ISO8601"
                          },
                          "duration": {
                            "type": "integer",
                            "description": "Numero di minuti di ampiezza dello slot."
                          },
                          "allowedPeople": {
                            "type": "integer",
                            "minimum": 0,
                            "description": "Numero di posti allocabili in quello slot."
                          },
                          "availablePlaces": {
                            "type": "integer",
                            "minimum": 0,
                            "description": "Numero di posti liberi in questo slot."
                          },
                          "allowBookingFrom": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Data e ora a partire dalla quale e possibile prenotare un posto nello slot selezionato."
                          },
                          "allowBookingUntil": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Data e ora fino alla quale e possibile prenotare un posto nello slot selezionato."
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/p/{placeId}/slots/{slotId}/bookings": {
      "parameters": [
        {
          "in": "path",
          "schema": {
            "type": "string"
          },
          "name": "placeId",
          "required": true
        },
        {
          "in": "path",
          "schema": {
            "type": "string"
          },
          "name": "slotId",
          "required": true
        }
      ],
      "post": {
        "tags": [
          "End User"
        ],
        "security": [
          {
            "userApiKey": []
          }
        ],
        "description": "Crea una nuova prenotazione per il luogo indicato, nello slot indicato",
        "requestBody": {
          "description": "La richiesta di prenotazione",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "people": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 3
                  },
                  "phone": {
                    "type": "string",
                    "description": "A valid phone number, no spaces, with international prefix."
                  },
                  "email": {
                    "type": "string",
                    "description": "A valid email to whom the booking will be sent.",
                    "format": "idn-email"
                  }
                },
                "oneOf": [
                  {
                    "required": [
                      "phone"
                    ]
                  },
                  {
                    "required": [
                      "email"
                    ]
                  }
                ],
                "required": [
                  "people"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Creata prenotazione",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "bookedPeople": {
                      "type": "integer",
                      "minimum": 1,
                      "maximum": 3
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/b/{bookingId}": {
      "parameters": [
        {
          "in": "path",
          "schema": {
            "type": "string"
          },
          "name": "bookingId",
          "required": true
        }
      ],
      "get": {
        "tags": [
          "End User"
        ],
        "security": [
          {
            "userApiKey": []
          }
        ],
        "description": "Ottieni le informazioni su una specifica prenotazione a partire dal suo ID",
        "responses": {
          "200": {
            "description": "Le informazioni sulla prenotazione",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "placeId": {
                      "type": "string"
                    },
                    "bookingId": {
                      "type": "string"
                    },
                    "startDatetime": {
                      "type": "string",
                      "format": "date-time",
                      "description": "Orario di inizio dello slot in UTC seguendo ISO8601"
                    },
                    "duration": {
                      "type": "integer",
                      "exclusiveMinimum": true,
                      "minimum": 0,
                      "description": "Ampiezza dello slot in minuti"
                    },
                    "bookedPeople": {
                      "type": "integer",
                      "exclusiveMinimum": true,
                      "minimum": 0,
                      "maximum": 3,
                      "description": "Numero di persone consentite"
                    },
                    "secretCode": {
                      "type": "string",
                      "minLength": 6,
                      "maxLength": 6,
                      "description": "Un codice casuale univoco per identificare l'utente se il booking ID non e leggibile con QR-scanner"
                    },
                    "entered": {
                      "type": "boolean",
                      "description": "Whether the booking has been used or not"
                    },
                    "place": {
                      "allOf": [
                        {
                          "type": "object",
                          "properties": {
                            "placeId": {
                              "type": "string"
                            },
                            "building": {
                              "type": "string"
                            },
                            "city": {
                              "type": "string"
                            },
                            "street": {
                              "type": "string"
                            },
                            "streetNumber": {
                              "type": "string"
                            },
                            "province": {
                              "type": "string"
                            },
                            "phone": {
                              "type": "string"
                            },
                            "lat": {
                              "type": "string"
                            },
                            "lon": {
                              "type": "string"
                            },
                            "category": {
                              "type": "string"
                            },
                            "name": {
                              "type": "string"
                            },
                            "website": {
                              "type": "string",
                              "format": "uri"
                            },
                            "istatCode": {
                              "type": "string"
                            },
                            "representative": {
                              "type": "string"
                            },
                            "cpu": {
                              "type": "string"
                            },
                            "openingTimeDesc": {
                              "type": "string",
                              "description": "La descrizione testuale degli orari di apertura"
                            },
                            "allowBookingByPhone": {
                              "type": "boolean",
                              "description": "Consentire o meno la registrazione tramite SMS",
                              "default": false
                            }
                          }
                        }
                      ],
                      "description": "Ancora in fase di valutazione se aggiungere tutto qui o lasciare che sia il frontend a fare due chiamate"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "End User"
        ],
        "security": [
          {
            "userApiKey": []
          }
        ],
        "description": "Elimina la prenotazione con l'ID indicato",
        "responses": {
          "204": {
            "description": "Annulla la prenotazione"
          }
        }
      }
    },
    "/search/p": {
      "get": {
        "tags": [
          "End User",
          "Search"
        ],
        "parameters": [
          {
            "name": "q",
            "in": "query",
            "description": "The text for full text search on all fields",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "near",
            "in": "query",
            "description": "Latitude and longitude for the search",
            "required": false,
            "schema": {
              "type": "string",
              "pattern": "\\d{1,2}(.\\d*)\\,\\d{1,2}(.\\d*)"
            }
          }
        ],
        "summary": "Search places",
        "description": "At least one of the 'q' or the 'near' parameters is required",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "places": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "placeId": {
                            "type": "string"
                          },
                          "building": {
                            "type": "string"
                          },
                          "city": {
                            "type": "string"
                          },
                          "street": {
                            "type": "string"
                          },
                          "streetNumber": {
                            "type": "string"
                          },
                          "province": {
                            "type": "string"
                          },
                          "phone": {
                            "type": "string"
                          },
                          "lat": {
                            "type": "string"
                          },
                          "lon": {
                            "type": "string"
                          },
                          "category": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "website": {
                            "type": "string",
                            "format": "uri"
                          },
                          "istatCode": {
                            "type": "string"
                          },
                          "representative": {
                            "type": "string"
                          },
                          "cpu": {
                            "type": "string"
                          },
                          "openingTimeDesc": {
                            "type": "string",
                            "description": "La descrizione testuale degli orari di apertura"
                          },
                          "allowBookingByPhone": {
                            "type": "boolean",
                            "description": "Consentire o meno la registrazione tramite SMS",
                            "default": false
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "userApiKey": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key"
      }
    },
    "schemas": {
      "PlaceList": {
        "type": "object",
        "properties": {
          "places": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "placeId": {
                  "type": "string"
                },
                "building": {
                  "type": "string"
                },
                "city": {
                  "type": "string"
                },
                "street": {
                  "type": "string"
                },
                "streetNumber": {
                  "type": "string"
                },
                "province": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "lat": {
                  "type": "string"
                },
                "lon": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "website": {
                  "type": "string",
                  "format": "uri"
                },
                "istatCode": {
                  "type": "string"
                },
                "representative": {
                  "type": "string"
                },
                "cpu": {
                  "type": "string"
                },
                "openingTimeDesc": {
                  "type": "string",
                  "description": "La descrizione testuale degli orari di apertura"
                },
                "allowBookingByPhone": {
                  "type": "boolean",
                  "description": "Consentire o meno la registrazione tramite SMS",
                  "default": false
                }
              }
            }
          }
        }
      },
      "PlaceInfo": {
        "type": "object",
        "properties": {
          "placeId": {
            "type": "string"
          },
          "building": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "street": {
            "type": "string"
          },
          "streetNumber": {
            "type": "string"
          },
          "province": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "lat": {
            "type": "string"
          },
          "lon": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "website": {
            "type": "string",
            "format": "uri"
          },
          "istatCode": {
            "type": "string"
          },
          "representative": {
            "type": "string"
          },
          "cpu": {
            "type": "string"
          },
          "openingTimeDesc": {
            "type": "string",
            "description": "La descrizione testuale degli orari di apertura"
          },
          "allowBookingByPhone": {
            "type": "boolean",
            "description": "Consentire o meno la registrazione tramite SMS",
            "default": false
          }
        }
      },
      "Slot": {
        "type": "object",
        "properties": {
          "slotId": {
            "type": "string",
            "description": "L'id dello specifico slot. E' univoco solamente per un determinato Place."
          },
          "startDatetime": {
            "type": "string",
            "format": "date-time",
            "description": "Orario di inizio dello slot in UTC seguendo ISO8601"
          },
          "duration": {
            "type": "integer",
            "description": "Numero di minuti di ampiezza dello slot."
          },
          "allowedPeople": {
            "type": "integer",
            "minimum": 0,
            "description": "Numero di posti allocabili in quello slot."
          },
          "availablePlaces": {
            "type": "integer",
            "minimum": 0,
            "description": "Numero di posti liberi in questo slot."
          },
          "allowBookingFrom": {
            "type": "string",
            "format": "date-time",
            "description": "Data e ora a partire dalla quale e possibile prenotare un posto nello slot selezionato."
          },
          "allowBookingUntil": {
            "type": "string",
            "format": "date-time",
            "description": "Data e ora fino alla quale e possibile prenotare un posto nello slot selezionato."
          }
        }
      },
      "SlotsResponse": {
        "type": "object",
        "properties": {
          "slots": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "slotId": {
                  "type": "string",
                  "description": "L'id dello specifico slot. E' univoco solamente per un determinato Place."
                },
                "startDatetime": {
                  "type": "string",
                  "format": "date-time",
                  "description": "Orario di inizio dello slot in UTC seguendo ISO8601"
                },
                "duration": {
                  "type": "integer",
                  "description": "Numero di minuti di ampiezza dello slot."
                },
                "allowedPeople": {
                  "type": "integer",
                  "minimum": 0,
                  "description": "Numero di posti allocabili in quello slot."
                },
                "availablePlaces": {
                  "type": "integer",
                  "minimum": 0,
                  "description": "Numero di posti liberi in questo slot."
                },
                "allowBookingFrom": {
                  "type": "string",
                  "format": "date-time",
                  "description": "Data e ora a partire dalla quale e possibile prenotare un posto nello slot selezionato."
                },
                "allowBookingUntil": {
                  "type": "string",
                  "format": "date-time",
                  "description": "Data e ora fino alla quale e possibile prenotare un posto nello slot selezionato."
                }
              }
            }
          }
        }
      },
      "BookingRequest": {
        "type": "object",
        "properties": {
          "people": {
            "type": "integer",
            "minimum": 1,
            "maximum": 3
          },
          "phone": {
            "type": "string",
            "description": "A valid phone number, no spaces, with international prefix."
          },
          "email": {
            "type": "string",
            "description": "A valid email to whom the booking will be sent.",
            "format": "idn-email"
          }
        },
        "oneOf": [
          {
            "required": [
              "phone"
            ]
          },
          {
            "required": [
              "email"
            ]
          }
        ],
        "required": [
          "people"
        ]
      },
      "BookingResponse": {
        "type": "object",
        "properties": {
          "bookedPeople": {
            "type": "integer",
            "minimum": 1,
            "maximum": 3
          }
        }
      },
      "BookingInfo": {
        "type": "object",
        "properties": {
          "placeId": {
            "type": "string"
          },
          "bookingId": {
            "type": "string"
          },
          "startDatetime": {
            "type": "string",
            "format": "date-time",
            "description": "Orario di inizio dello slot in UTC seguendo ISO8601"
          },
          "duration": {
            "type": "integer",
            "exclusiveMinimum": true,
            "minimum": 0,
            "description": "Ampiezza dello slot in minuti"
          },
          "bookedPeople": {
            "type": "integer",
            "exclusiveMinimum": true,
            "minimum": 0,
            "maximum": 3,
            "description": "Numero di persone consentite"
          },
          "secretCode": {
            "type": "string",
            "minLength": 6,
            "maxLength": 6,
            "description": "Un codice casuale univoco per identificare l'utente se il booking ID non e leggibile con QR-scanner"
          },
          "entered": {
            "type": "boolean",
            "description": "Whether the booking has been used or not"
          },
          "place": {
            "allOf": [
              {
                "type": "object",
                "properties": {
                  "placeId": {
                    "type": "string"
                  },
                  "building": {
                    "type": "string"
                  },
                  "city": {
                    "type": "string"
                  },
                  "street": {
                    "type": "string"
                  },
                  "streetNumber": {
                    "type": "string"
                  },
                  "province": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string"
                  },
                  "lat": {
                    "type": "string"
                  },
                  "lon": {
                    "type": "string"
                  },
                  "category": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "website": {
                    "type": "string",
                    "format": "uri"
                  },
                  "istatCode": {
                    "type": "string"
                  },
                  "representative": {
                    "type": "string"
                  },
                  "cpu": {
                    "type": "string"
                  },
                  "openingTimeDesc": {
                    "type": "string",
                    "description": "La descrizione testuale degli orari di apertura"
                  },
                  "allowBookingByPhone": {
                    "type": "boolean",
                    "description": "Consentire o meno la registrazione tramite SMS",
                    "default": false
                  }
                }
              }
            ],
            "description": "Ancora in fase di valutazione se aggiungere tutto qui o lasciare che sia il frontend a fare due chiamate"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "End User",
      "description": "Chiamate utilizzate dall'end user, non sono autenticate."
    },
    {
      "name": "Search",
      "description": "Chiamate per cercare i luoghi"
    }
  ]
}